jobs:
  get_maintainers:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 10
    - continue-on-error: true
      name: Get commit branch and commit message from PR
      run: 'echo "BRANCH_NAME=$GITHUB_HEAD_REF" >> $GITHUB_ENV

        echo "TARGET_BRANCH_NAME=$(echo ${GITHUB_BASE_REF##*/})" >> $GITHUB_ENV

        echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV

        echo "$(git log --format=%B -n 1 HEAD^2)" >> $GITHUB_ENV

        echo "EOF" >> $GITHUB_ENV

        echo "PREVIOUS_COMMIT=$(git log --format=%H -n 1 HEAD^2~1)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: '3.10'
    - continue-on-error: true
      name: Save PR number
      run: 'mkdir -p ./maintainers

        echo ${{ github.event.number }} > ./maintainers/NR

        '
    - continue-on-error: true
      name: Get Maintainers
      run: 'python ./toolset/github_actions/get_maintainers.py > ./maintainers/maintainers.md

        '
    - continue-on-error: true
      name: Save Maintainers
      uses: actions/upload-artifact@v4
      with:
        name: maintainers
        path: maintainers/
name: get-maintainers
on:
  repository_dispatch:
    types: trigger-ga___get-maintainers.yml
permissions:
  pull-requests: write
