jobs:
  apply_label:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion
      == 'failure' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifact
      uses: actions/github-script@v7
      with:
        script: "var artifacts = await github.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nvar matchArtifact = artifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == \"pr\"\n})[0];\nvar download = await github.actions.downloadArtifact({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   artifact_id:\
          \ matchArtifact.id,\n   archive_format: 'zip',\n});\nvar fs = require('fs');\n\
          fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));\n"
    - continue-on-error: true
      run: unzip pr.zip
    - continue-on-error: true
      name: Label PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "var fs = require('fs');\nvar issue_number = Number(fs.readFileSync('./NR'));\n\
          await github.issues.addLabels({\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n\
          \  issue_number: issue_number,\n  labels: ['PR: Please Update']\n});\n"
name: Label PR if failed
on:
  repository_dispatch:
    types: trigger-ga___label-failing-pr.yml
