jobs:
  ping_maintainers:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download maintainers artifact
      uses: actions/github-script@v7
      with:
        script: "let artifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ ${{github.event.workflow_run.id }},\n});\nlet matchArtifact = artifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == \"maintainers\"\n})[0];\nlet download\
          \ = await github.rest.actions.downloadArtifact({\n   owner: context.repo.owner,\n\
          \   repo: context.repo.repo,\n   artifact_id: matchArtifact.id,\n   archive_format:\
          \ 'zip',\n});\nlet fs = require('fs');\nfs.writeFileSync('${{github.workspace}}/maintainers.zip',\
          \ Buffer.from(download.data));\n"
    - continue-on-error: true
      run: unzip maintainers.zip
    - continue-on-error: true
      name: Ping maintainers
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "let fs = require('fs');\nlet issue_number = Number(fs.readFileSync('./NR'));\n\
          let maintainers_comment = fs.readFileSync('./maintainers.md', 'utf8');\n\
          if (maintainers_comment) {\n  await github.rest.issues.createComment({\n\
          \    issue_number: issue_number,\n    owner: context.repo.owner,\n    repo:\
          \ context.repo.repo,\n    body: maintainers_comment\n  });\n}\n"
name: Ping Maintainers
on:
  repository_dispatch:
    types: trigger-ga___ping-maintainers.yml
permissions:
  pull-requests: write
